# Generated by Django 6.0.3 on 2026-04-19 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_teamleader_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamleader',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='teamleader',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_leader_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
