# Generated by Django 6.0.3 on 2026-04-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
