# Generated by Django 6.0.3 on 2026-04-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, choices=[('OpenAlex', 'OpenAlex'), ('Scopus', 'Scopus'), ('Wos', 'Web of Science'), ('Crossref', 'Crossref'), ('Dimensions', 'Dimensions')], max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('citation_date', models.DateField(blank=True, null=True)),
                ('openalex_id', models.CharField(blank=True, db_index=True, help_text='ID OpenAlex de la citation : https://openalex.org/C1234567890', max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Citation',
                'verbose_name_plural': 'Citations',
                'db_table': 'citations',
            },
        ),
    ]
