# Generated by Django 6.0.3 on 2026-04-02 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citation', '0001_initial'),
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='cited_publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations_received', to='publication.publication'),
        ),
        migrations.AddField(
            model_name='citation',
            name='citing_publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations_made', to='publication.publication'),
        ),
        migrations.AlterUniqueTogether(
            name='citation',
            unique_together={('citing_publication', 'cited_publication')},
        ),
    ]
