# Generated by Django 6.0.3 on 2026-04-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoAuthor',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(help_text="اسم المؤلف من OpenAlex / Nom de l'auteur depuis OpenAlex", max_length=255)),
                ('author_orcid', models.CharField(blank=True, db_index=True, help_text="ORCID ID if available / ORCID ID s'il est disponible", max_length=50, null=True)),
                ('openalex_id', models.CharField(blank=True, help_text='OpenAlex author ID / ID auteur OpenAlex', max_length=100, null=True)),
                ('contribution_type', models.IntegerField(choices=[(1, 'First Author'), (2, 'Second Author'), (3, 'Third Author'), (4, 'Corresponding Author'), (5, 'Other')], default=1)),
                ('author_order', models.IntegerField(default=1, help_text="ترتيب المؤلف في المنشور / Ordre de l'auteur dans la publication")),
                ('affiliation_at_time', models.CharField(blank=True, help_text='انتماء المؤلف وقت النشر / Affiliation au moment de la publication', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CoAuthor',
                'verbose_name_plural': 'CoAuthors',
                'db_table': 'coauthors',
                'ordering': ['author_order'],
            },
        ),
    ]
