# Generated by Django 6.0.3 on 2026-04-02 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coAuthor', '0001_initial'),
        ('publication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coauthor',
            name='linked_user',
            field=models.ForeignKey(blank=True, help_text='Link to User if they registered / الارتباط بـ User إذا تسجلوا', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coauthor_credits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coauthor',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coauthors', to='publication.publication'),
        ),
        migrations.AddIndex(
            model_name='coauthor',
            index=models.Index(fields=['author_orcid', 'publication'], name='coauthors_author__26bbbd_idx'),
        ),
        migrations.AddIndex(
            model_name='coauthor',
            index=models.Index(fields=['linked_user'], name='coauthors_linked__ff7267_idx'),
        ),
        migrations.AddIndex(
            model_name='coauthor',
            index=models.Index(fields=['openalex_id'], name='coauthors_openale_cb27e6_idx'),
        ),
    ]
