# Generated by Django 6.0.3 on 2026-04-02 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0001_initial'),
        ('journal', '0001_initial'),
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('abstract', models.TextField(blank=True)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('type', models.CharField(choices=[('Article', 'Article'), ('Book', 'Livre'), ('Conference_Paper', 'Communication en conférence'), ('Review', 'Revue')], default='Article', max_length=20)),
                ('citation_count', models.IntegerField(default=0)),
                ('altmetric_score', models.FloatField(blank=True, null=True)),
                ('is_validated', models.BooleanField(default=True)),
                ('openalex_id', models.CharField(blank=True, help_text='ID OpenAlex : https://openalex.org/W1234567890', max_length=200, null=True, unique=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='institution.institution')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='journal.journal')),
                ('keywords', models.ManyToManyField(blank=True, related_name='publications', to='keywords.keyword')),
            ],
            options={
                'db_table': 'publications_publication',
            },
        ),
    ]
