# Generated by Django 6.0.3 on 2026-04-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publication', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='reseachers',
            field=models.ManyToManyField(blank=True, related_name='publications', to='users.researcher'),
        ),
    ]
