# Generated by Django 6.0.3 on 2026-04-02 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'country',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'ville',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('University', 'Université'), ('Research_Center', 'Centre de Recherche'), ('University_Center', 'Centre Universitaire'), ('Ecole', 'Ecole')], max_length=20)),
                ('website', models.URLField(blank=True)),
                ('ville', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions', to='institution.ville')),
            ],
            options={
                'db_table': 'institution',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wilayas', to='institution.country')),
            ],
            options={
                'db_table': 'wilaya',
                'ordering': ['name'],
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.AddField(
            model_name='ville',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villes', to='institution.wilaya'),
        ),
        migrations.AlterUniqueTogether(
            name='ville',
            unique_together={('name', 'wilaya')},
        ),
    ]
