# Generated by Django 6.0.3 on 2026-04-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'publications_keyword',
            },
        ),
    ]
