# Generated by Django 6.0.3 on 2026-04-20 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_teamleader_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibliometricJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Progression en %')),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bibliometric_jobs', to='users.researcher')),
            ],
            options={
                'db_table': 'bibliometric_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearcherBibliometricCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_index', models.IntegerField(default=0, help_text='H-index')),
                ('g_index', models.IntegerField(default=0, help_text='G-index')),
                ('m_index', models.FloatField(default=0.0, help_text='M-index = H-index / années actives')),
                ('total_papers', models.IntegerField(default=0)),
                ('total_citations', models.IntegerField(default=0)),
                ('avg_citations_per_paper', models.FloatField(default=0.0)),
                ('yearly_output', models.JSONField(default=dict, help_text='Publications par année')),
                ('yearly_citations', models.JSONField(default=dict, help_text='Citations par année')),
                ('top_keywords', models.JSONField(default=list, help_text='Top 20 mots-clés')),
                ('top_journals', models.JSONField(default=list, help_text='Top 10 journaux')),
                ('collaboration_network', models.JSONField(default=dict, help_text='Réseau de co-auteurs')),
                ('keyword_network', models.JSONField(default=dict, help_text='Réseau de mots-clés')),
                ('first_publication_year', models.IntegerField(blank=True, null=True)),
                ('last_publication_year', models.IntegerField(blank=True, null=True)),
                ('years_active', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('researcher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bibliometric_cache', to='users.researcher')),
            ],
            options={
                'verbose_name': 'Cache Bibliométrique',
                'verbose_name_plural': 'Caches Bibliométriques',
                'db_table': 'bibliometric_cache',
                'indexes': [models.Index(fields=['researcher', 'updated_at'], name='bibliometri_researc_387f4c_idx'), models.Index(fields=['h_index'], name='bibliometri_h_index_13f7a1_idx')],
            },
        ),
    ]
