# Generated by Django 6.0.3 on 2026-04-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliometric', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibliometrixAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('summary', 'Résumé global'), ('top_authors', 'Top auteurs'), ('thematic_clusters', 'Clusters thématiques'), ('collaboration_network', 'Réseau collaboration'), ('thematic_evolution', 'Évolution thématique'), ('cocitation', 'Co-citation'), ('coupling', 'Coupling bibliographique'), ('foundational_works', 'Publications fondatrices'), ('author_metrics', 'Métriques auteur')], max_length=50)),
                ('parameters', models.JSONField(default=dict)),
                ('results', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bibliometrix_analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='bibliometricjob',
            name='researcher',
        ),
        migrations.AlterModelOptions(
            name='researcherbibliometriccache',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='researcherbibliometriccache',
            name='bibliometri_researc_387f4c_idx',
        ),
        migrations.RemoveIndex(
            model_name='researcherbibliometriccache',
            name='bibliometri_h_index_13f7a1_idx',
        ),
        migrations.RenameField(
            model_name='researcherbibliometriccache',
            old_name='avg_citations_per_paper',
            new_name='avg_citations',
        ),
        migrations.AlterField(
            model_name='researcherbibliometriccache',
            name='collaboration_network',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='researcherbibliometriccache',
            name='g_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='researcherbibliometriccache',
            name='h_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='researcherbibliometriccache',
            name='m_index',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='researcherbibliometriccache',
            name='top_journals',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='researcherbibliometriccache',
            name='top_keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='researcherbibliometriccache',
            name='yearly_citations',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='researcherbibliometriccache',
            name='yearly_output',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='BibliometricJob',
        ),
        migrations.RemoveField(
            model_name='researcherbibliometriccache',
            name='keyword_network',
        ),
    ]
