# Generated by Django 6.0.3 on 2026-04-20 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliometric', '0002_bibliometrixanalysis_and_more'),
        ('users', '0003_alter_teamleader_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibliometrixAnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_index', models.IntegerField()),
                ('total_papers', models.IntegerField()),
                ('total_citations', models.IntegerField()),
                ('avg_citations', models.FloatField()),
                ('analysis_date', models.DateField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'bibliometric_history',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='researcherbibliometriccache',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='bibliometrixanalysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bibliometrixanalysis',
            name='analysis_type',
            field=models.CharField(choices=[('summary', 'Résumé global'), ('top_authors', 'Top auteurs'), ('thematic_clusters', 'Clusters thématiques'), ('collaboration_network', 'Réseau collaboration'), ('thematic_evolution', 'Évolution thématique'), ('cocitation', 'Co-citation'), ('coupling', 'Coupling bibliographique'), ('foundational_works', 'Publications fondatrices'), ('author_metrics', 'Métriques auteur')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bibliometrixanalysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='researcherbibliometriccache',
            name='collaboration_network',
            field=models.JSONField(default=dict, help_text='Données réseau collaboration'),
        ),
        migrations.AlterField(
            model_name='researcherbibliometriccache',
            name='h_index',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='researcherbibliometriccache',
            name='top_journals',
            field=models.JSONField(default=list, help_text='Top 10 revues'),
        ),
        migrations.AlterField(
            model_name='researcherbibliometriccache',
            name='top_keywords',
            field=models.JSONField(default=list, help_text='Top 10 mots-clés'),
        ),
        migrations.AlterField(
            model_name='researcherbibliometriccache',
            name='total_papers',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='researcherbibliometriccache',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='researcherbibliometriccache',
            name='yearly_citations',
            field=models.JSONField(default=dict, help_text='Citations par année'),
        ),
        migrations.AlterField(
            model_name='researcherbibliometriccache',
            name='yearly_output',
            field=models.JSONField(default=dict, help_text='Distribution des publications par année'),
        ),
        migrations.AddIndex(
            model_name='bibliometrixanalysis',
            index=models.Index(fields=['analysis_type', '-created_at'], name='bibliometri_analysi_235952_idx'),
        ),
        migrations.AddIndex(
            model_name='researcherbibliometriccache',
            index=models.Index(fields=['h_index', '-total_papers'], name='bibliometri_h_index_971c93_idx'),
        ),
        migrations.AddIndex(
            model_name='researcherbibliometriccache',
            index=models.Index(fields=['updated_at'], name='bibliometri_updated_4bb46e_idx'),
        ),
        migrations.AddField(
            model_name='bibliometrixanalysishistory',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bibliometric_history', to='users.researcher'),
        ),
        migrations.AlterUniqueTogether(
            name='bibliometrixanalysishistory',
            unique_together={('researcher', 'analysis_date')},
        ),
    ]
